### ISSUE TITLE
fromNumber is unsafe

### ISSUE THREAD

**Issue by maddie927** [sharkdp/purescript-bigints#18]
For example, `fromNumber infinity`. Does it make sense to change it to `fromNumber :: Number -> Maybe BigInt`?

**Comment by sharkdp** [comment]
You are right.

I think this should only happen for `Infinity` and `NaN`, though. Otherwise, it works for the highest possible JavaScript numbers (~`1.0e308`).

Changing the type signature to `Maybe BigInt` would be a breaking change, which we could potentially introduce when we update for PS 0.12 anyways.

Another option would be to accept these two failure cases and to add a warning to the documentation. In addition, we could provide a safe version that returns a `Maybe BigInt`.

What do you think?

**Comment by maddie927** [comment]
I would guess most are unlikely to think about it until it explodes unexpectedly, so I favor the breaking change for safety. :slightly_smiling_face: Having other breaking changes for PS 0.12 at the same time is convenient as well.

I can send a PR soon if you agree.
